name: PyInstaller Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Compile the Python script into a binary
      - name: Compile to binary
        run: |
          pyinstaller --onefile tpet.py

      # Archive the build output
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: tpet-binary
          path: dist/tpet

